language: c

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - check

script: mkdir build && cd build && cmake .. -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1 && make && make test
