language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y check

script: mkdir build && cd build && cmake .. -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1 && make
